export const ROUTES = {
  login: '/login',
  professorLogin: '/professor-login',
  professorVerify: '/professor-login/verify',
  projects: '/admin/projects',
  professorProjects: '/admin/projects',
  professorAnalytics: '/admin/analytics',
  people: '/admin/people',
  professors: '/admin/professors',
  students: '/admin/students',
  careers: '/admin/careers',
  applicationDomains: '/admin/application-domains',
  tags: '/admin/tags',
  backup: '/admin/backup',
  importData: '/admin/import-data',
  export: '/admin/export',
}
